name: Add Jira Details to PR

on:
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  append_jira_details:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
      - name: Append Jira Details to PR
        uses: ar-ushi/append-jira-details-action@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          orgUrl: "https://mock-jira-enterprise.atlassian.net"
          jiraToken: ${{ secrets.JIRA_TOKEN }}
          username: ${{ secrets.PR_USERNAME }}
          jiraKey: "MOE,LOSIM,TES"
