name: "Add Jira Details to PR"
on:
  workflow_run:
    workflows: ["PR Tasks Completed Check"] # Name of the first workflow
    types:
      - completed # This triggers the workflow when the first one completes

jobs:
  dependent-task:
    runs-on: ubuntu-latest
    steps:
      - name: Append Jira Details to PR
        uses: ar-ushi/append-jira-details-action@v1.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          orgUrl: "https://mock-jira-enterprise.atlassian.net"
          jiraToken: ${{ secrets.JIRA_TOKEN }}
          username: ${{ secrets.PR_USERNAME }}
          jiraKey: "MOE,LOSIM"
