name: Update PR with Jira Ticket details
on: pull_request
jobs:
  update_pr_description:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Extract Ticket ID from Branch Name
        id: get_jid
        run: |
          branch_name=${{ github.event.pull_request.head.ref }}
          jiraId=$( echo "$branch_name" | cut -d'/' -f1)
          echo "set_output name=jira_id:::$(jiraId)" >> $GITHUB_OUTPUT
      - name : actions
        id : typescript
        uses: ./
        with: 
          token: ${{ secrets.GITHUB_TOKEN }}
          jiraId: MOE-1
          orgUrl: 'https://mock-jira-enterprise.atlassian.net'
          jiraToken: ${{ secrets.JIRA_TOKEN }}
          username: ${{ secrets.PR_USERNAME }}