name: Update PR with Jira Ticket details
on: pull_request
jobs:
  update_pr_description:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Update PR with Jira Ticket details
        id: typescript
        uses: ./
        with: 
          token: ${{ secrets.GITHUB_TOKEN }}
          orgUrl: 'https://mock-enterprise.atlassian.net'
          jiraToken: ${{ secrets.JIRA_TOKEN }}
          username: ${{ secrets.PR_USERNAME }}
          jiraKey: |
            - MOE
